<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="/common/common.jsp" %>
<%@ include file="/common/function.jsp" %>
<%@ page import="java.net.URL"%>
<%@ page import="java.net.HttpURLConnection"%>
<%@ page import="java.io.InputStream"%>
<%@ page import="java.io.BufferedOutputStream"%>
<%@ page import="wfm.com.util.AES256Cipher"%>
<%
	// DB Connection Object
	Db db = null;

	try {
		// DB Connection
		db = new Db(true);

		// get parameter
		String rec_datm = request.getParameter("rec_datm");
		String rec_filename = request.getParameter("rec_keycode2");
		String reason_code = CommonUtil.getParameter("reason_code");
		String reason_text = CommonUtil.getParameter("reason_text");

		// 파라미터 체크
		if(!CommonUtil.hasText(rec_datm) || !CommonUtil.hasText(rec_filename) || !CommonUtil.hasText(reason_code)) {
			out.print("ERR" + CommonUtil.getErrorMsg("NO_PARAM"));
			return;
		}

		// parameter decrypt
		AES256Cipher a256 = AES256Cipher.getInstance(CommonUtil.getWfmEncKey());

		String dec_rec_datm = a256.decrypt(rec_datm);
		String dec_rec_filename = a256.decrypt(rec_filename) + ".wav";

		//
		Map<String, Object> argMap = new HashMap<String, Object>();

		// yyyyMMddHHmmssSSS -> yyyy-MM-dd HH:mm:ss.SSS
		//dec_rec_datm = DateUtil.getDateFormatByIntVal(dec_rec_datm, "yyyy-MM-dd HH:mm:ss");

		//
		argMap.clear();
		argMap.put("dateStr", CommonUtil.getRecordTableNm(dec_rec_datm));
		argMap.put("rec_date",dec_rec_datm);
		argMap.put("rec_filename",dec_rec_filename);

		// 녹취이력 조회
		Map<String, Object> data  = db.selectOne("rec_search.selectItem", argMap);
		if(data==null) {
			out.print("ERR" + CommonUtil.getErrorMsg("NO_DATA"));
			return;
		}

		// 녹취파일 경로 조회
		String file_url = getListenURL("PCM", data, logger);

		if(file_url==null || "".equals(file_url)) {
			out.print("ERR" + "녹취파일 경로를 가져 오는데 실패했습니다.");
			return;
		}

		if("ERR".equals(file_url.substring(0,3))) {
			out.print("ERR" + file_url.substring(3));
			return;
		}

		// 녹취파일 HTTP 연결
		URL url = new URL(file_url);

		HttpURLConnection httpconn = (HttpURLConnection) url.openConnection();
		httpconn.setConnectTimeout(10000);
		//timeout으로 인한 주석 처리
		//httpconn.setReadTimeout(60000);

		if(httpconn.getResponseCode()!=HttpURLConnection.HTTP_OK) {
			out.print("ERR" + "녹취파일이 존재하지 않습니다.");
			return;
		}

		String contentType = httpconn.getContentType();
		int contentLength = httpconn.getContentLength();

		response.reset();
		response.setContentType(contentType);
		response.setHeader("Content-Description","Generated By CREC");
		response.setHeader("Content-Disposition","attachment; filename = " + new String(data.get("rec_filename").toString().getBytes("UTF-8"),"8859_1"));
		response.setHeader("Content-Length",""+contentLength);
		response.setHeader("Pragma","no-cache");
		response.setHeader("Expires","0");
		response.setHeader("Cache-Control","max-age=0");

		InputStream in = httpconn.getInputStream();

		// getOutputStream error block
		out.clear();
		out=pageContext.pushBody();

		// file write
		BufferedOutputStream os = new BufferedOutputStream(response.getOutputStream());
		int leng = 0;
		while((leng=in.read())!=-1) {
			os.write(leng);
		}

		os.close();
		in.close();
		httpconn.disconnect();

		// 다운로드 이력 저장
		argMap.put("login_id","");
		argMap.put("login_name","");
		argMap.put("rec_datm",data.get("rec_datm").toString());
		argMap.put("local_no",data.get("local_no").toString());
		argMap.put("rec_filename",data.get("rec_filename").toString());
		argMap.put("down_ip",request.getRemoteAddr());
		argMap.put("rec_keycode",data.get("rec_keycode").toString());
		argMap.put("user_id",data.get("user_id").toString());
		argMap.put("user_name",data.get("user_name").toString());
		argMap.put("reason_code",reason_code);
		argMap.put("reason_text",reason_text);
		argMap.put("down_src","AP");

		int ins_cnt = db.insert("hist_down.insertDownHist", argMap);
	} catch(Exception e) {
		out.print("ERR" + e.getMessage());
		logger.error(e.getMessage());
	} finally {
		if(db!=null) db.close();
	}
%>